/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DepositPendingIdRouteImport } from './routes/deposit-pending.$id'
import { Route as DashboardWithdrawRouteImport } from './routes/dashboard.withdraw'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardInvestRouteImport } from './routes/dashboard.invest'
import { Route as DashboardDepositProofRouteImport } from './routes/dashboard.deposit-proof'
import { Route as DashboardDepositPaymentRouteImport } from './routes/dashboard.deposit-payment'
import { Route as DashboardDepositRouteImport } from './routes/dashboard.deposit'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminMethodsRouteImport } from './routes/admin.methods'
import { Route as AdminInvestmentsRouteImport } from './routes/admin.investments'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as InvestSuccessIdRouteImport } from './routes/invest.success.$id'
import { Route as InvestConfirmPlanIdRouteImport } from './routes/invest.confirm.$planId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DepositPendingIdRoute = DepositPendingIdRouteImport.update({
  id: '/deposit-pending/$id',
  path: '/deposit-pending/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWithdrawRoute = DashboardWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvestRoute = DashboardInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepositProofRoute = DashboardDepositProofRouteImport.update({
  id: '/deposit-proof',
  path: '/deposit-proof',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepositPaymentRoute = DashboardDepositPaymentRouteImport.update({
  id: '/deposit-payment',
  path: '/deposit-payment',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepositRoute = DashboardDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMethodsRoute = AdminMethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvestmentsRoute = AdminInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const InvestSuccessIdRoute = InvestSuccessIdRouteImport.update({
  id: '/invest/success/$id',
  path: '/invest/success/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestConfirmPlanIdRoute = InvestConfirmPlanIdRouteImport.update({
  id: '/invest/confirm/$planId',
  path: '/invest/confirm/$planId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/methods': typeof AdminMethodsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/deposit-payment': typeof DashboardDepositPaymentRoute
  '/dashboard/deposit-proof': typeof DashboardDepositProofRoute
  '/dashboard/invest': typeof DashboardInvestRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/withdraw': typeof DashboardWithdrawRoute
  '/deposit-pending/$id': typeof DepositPendingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/invest/confirm/$planId': typeof InvestConfirmPlanIdRoute
  '/invest/success/$id': typeof InvestSuccessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/methods': typeof AdminMethodsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/deposit-payment': typeof DashboardDepositPaymentRoute
  '/dashboard/deposit-proof': typeof DashboardDepositProofRoute
  '/dashboard/invest': typeof DashboardInvestRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/withdraw': typeof DashboardWithdrawRoute
  '/deposit-pending/$id': typeof DepositPendingIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/invest/confirm/$planId': typeof InvestConfirmPlanIdRoute
  '/invest/success/$id': typeof InvestSuccessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/investments': typeof AdminInvestmentsRoute
  '/admin/methods': typeof AdminMethodsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/dashboard/deposit': typeof DashboardDepositRoute
  '/dashboard/deposit-payment': typeof DashboardDepositPaymentRoute
  '/dashboard/deposit-proof': typeof DashboardDepositProofRoute
  '/dashboard/invest': typeof DashboardInvestRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/withdraw': typeof DashboardWithdrawRoute
  '/deposit-pending/$id': typeof DepositPendingIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/invest/confirm/$planId': typeof InvestConfirmPlanIdRoute
  '/invest/success/$id': typeof InvestSuccessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/plans'
    | '/register'
    | '/reset-password'
    | '/admin/deposits'
    | '/admin/emails'
    | '/admin/investments'
    | '/admin/methods'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/dashboard/deposit'
    | '/dashboard/deposit-payment'
    | '/dashboard/deposit-proof'
    | '/dashboard/invest'
    | '/dashboard/profile'
    | '/dashboard/wallet'
    | '/dashboard/withdraw'
    | '/deposit-pending/$id'
    | '/admin/'
    | '/dashboard/'
    | '/invest/confirm/$planId'
    | '/invest/success/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/plans'
    | '/register'
    | '/reset-password'
    | '/admin/deposits'
    | '/admin/emails'
    | '/admin/investments'
    | '/admin/methods'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/dashboard/deposit'
    | '/dashboard/deposit-payment'
    | '/dashboard/deposit-proof'
    | '/dashboard/invest'
    | '/dashboard/profile'
    | '/dashboard/wallet'
    | '/dashboard/withdraw'
    | '/deposit-pending/$id'
    | '/admin'
    | '/dashboard'
    | '/invest/confirm/$planId'
    | '/invest/success/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/plans'
    | '/register'
    | '/reset-password'
    | '/admin/deposits'
    | '/admin/emails'
    | '/admin/investments'
    | '/admin/methods'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/dashboard/deposit'
    | '/dashboard/deposit-payment'
    | '/dashboard/deposit-proof'
    | '/dashboard/invest'
    | '/dashboard/profile'
    | '/dashboard/wallet'
    | '/dashboard/withdraw'
    | '/deposit-pending/$id'
    | '/admin/'
    | '/dashboard/'
    | '/invest/confirm/$planId'
    | '/invest/success/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PlansRoute: typeof PlansRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DepositPendingIdRoute: typeof DepositPendingIdRoute
  InvestConfirmPlanIdRoute: typeof InvestConfirmPlanIdRoute
  InvestSuccessIdRoute: typeof InvestSuccessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/deposit-pending/$id': {
      id: '/deposit-pending/$id'
      path: '/deposit-pending/$id'
      fullPath: '/deposit-pending/$id'
      preLoaderRoute: typeof DepositPendingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/withdraw': {
      id: '/dashboard/withdraw'
      path: '/withdraw'
      fullPath: '/dashboard/withdraw'
      preLoaderRoute: typeof DashboardWithdrawRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invest': {
      id: '/dashboard/invest'
      path: '/invest'
      fullPath: '/dashboard/invest'
      preLoaderRoute: typeof DashboardInvestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deposit-proof': {
      id: '/dashboard/deposit-proof'
      path: '/deposit-proof'
      fullPath: '/dashboard/deposit-proof'
      preLoaderRoute: typeof DashboardDepositProofRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deposit-payment': {
      id: '/dashboard/deposit-payment'
      path: '/deposit-payment'
      fullPath: '/dashboard/deposit-payment'
      preLoaderRoute: typeof DashboardDepositPaymentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deposit': {
      id: '/dashboard/deposit'
      path: '/deposit'
      fullPath: '/dashboard/deposit'
      preLoaderRoute: typeof DashboardDepositRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/methods': {
      id: '/admin/methods'
      path: '/methods'
      fullPath: '/admin/methods'
      preLoaderRoute: typeof AdminMethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/investments': {
      id: '/admin/investments'
      path: '/investments'
      fullPath: '/admin/investments'
      preLoaderRoute: typeof AdminInvestmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/invest/success/$id': {
      id: '/invest/success/$id'
      path: '/invest/success/$id'
      fullPath: '/invest/success/$id'
      preLoaderRoute: typeof InvestSuccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest/confirm/$planId': {
      id: '/invest/confirm/$planId'
      path: '/invest/confirm/$planId'
      fullPath: '/invest/confirm/$planId'
      preLoaderRoute: typeof InvestConfirmPlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminInvestmentsRoute: typeof AdminInvestmentsRoute
  AdminMethodsRoute: typeof AdminMethodsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDepositsRoute: AdminDepositsRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminInvestmentsRoute: AdminInvestmentsRoute,
  AdminMethodsRoute: AdminMethodsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardDepositRoute: typeof DashboardDepositRoute
  DashboardDepositPaymentRoute: typeof DashboardDepositPaymentRoute
  DashboardDepositProofRoute: typeof DashboardDepositProofRoute
  DashboardInvestRoute: typeof DashboardInvestRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardWithdrawRoute: typeof DashboardWithdrawRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDepositRoute: DashboardDepositRoute,
  DashboardDepositPaymentRoute: DashboardDepositPaymentRoute,
  DashboardDepositProofRoute: DashboardDepositProofRoute,
  DashboardInvestRoute: DashboardInvestRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardWithdrawRoute: DashboardWithdrawRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PlansRoute: PlansRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DepositPendingIdRoute: DepositPendingIdRoute,
  InvestConfirmPlanIdRoute: InvestConfirmPlanIdRoute,
  InvestSuccessIdRoute: InvestSuccessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
